Filter out coverage of generated call from implementer to default interface method(alternative)
JetBrains/intellij-coverage pull request #10
Opened 2020-10-08 14:28 UTC by zuevmaxim

Here a Filter has no access to instructions list because instrumenting visitors do not extend MethodNode, as it causes more memory and time consumption. Therefore, filters have to decide whether to filter while visiting. 
Note: it seems like an overhead of visitor calls when there are too many Filters(I think it's not the case).
Note2: filtered lines are ignored, but extra instrumentation is added anyway
Note3: ClassInstrumenter already extends MethodNode

2020-10-09 15:14 UTC, gorrus requested changes

2020-10-09 15:14 UTC, gorrus commented on instrumentation/src/com/intellij/rt/coverage/instrumentation/filters/ImplementerDefaultInterfaceMemberFilter.java
> +public class ImplementerDefaultInterfaceMemberFilter extends MethodFilter {
This is only about kotlin, maybe it is better the class name contain kotlin word?
Or put this into a kotin-something package.

2020-10-16 10:58 UTC, akozlova approved these changes

2020-10-16 18:16 UTC, gorrus approved these changes

2020-10-26 17:03 UTC, zuevmaxim commented
Now `isKotlinClass` check is extracted

2020-10-27 13:46 UTC, akozlova approved these changes

2020-11-03 10:34 UTC, merged